name: Update readme Tech Stack
on:
  schedule:
    - cron: "0 18 * * *"
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run JS
        run: node readme.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet && echo "No changes" || (
            git add readme.md &&
            git commit -m "Auto update tech stack [skip ci]" &&
            git push
          )